/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "outline-variant": "#812b2d",
          "surface-container-high": "#2e353f",
          "on-primary-container": "#00626e",
          "on-secondary-fixed": "#0f1c2c",
          "primary-fixed-dim": "#00daf3",
          "on-primary-fixed-variant": "#004f58",
          "inverse-on-surface": "#2a313b",
          "surface-bright": "#333a44",
          "primary-fixed": "#9cf0ff",
          "error": "#FF8EBE",
          "tertiary-fixed": "#ffdcc3",
          "surface-dim": "#0d141d",
          "surface-container-highest": "#3a424e",
          "secondary-fixed": "#d6e4f9",
          "secondary": "#ef574e",
          "on-secondary-fixed-variant": "#3a4859",
          "on-primary-fixed": "#001f24",
          "on-tertiary-fixed": "#2f1500",
          "on-tertiary": "#4d2600",
          "primary": "#57e6ef",
          "inverse-primary": "#006875",
          "on-primary": "#00363d",
          "tertiary-fixed-dim": "#ffb77d",
          "on-secondary-container": "#a8b6ca",
          "on-background": "#dce3f0",
          "surface-container-lowest": "#151c26",
          "on-tertiary-container": "#894800",
          "on-surface": "#dce3f0",
          "surface-container-low": "#19202a",
          "secondary-container": "#3a4859",
          "surface-container": "#242a34",
          "outline": "#849396",
          "background": "#0d141d",
          "tertiary": "#812b2d",
          "secondary-fixed-dim": "#bac8dc",
          "inverse-surface": "#dce3f0",
          "primary-container": "#00e5ff",
          "surface-tint": "#00daf3",
          "surface": "#0d141d",
          "on-secondary": "#243141",
          "on-surface-variant": "#bac9cc",
          "surface-variant": "#2e353f",
          "tertiary-container": "#ffc598",
          "surface-matte": "#12111A",
          "accent-green": "#1df283",
          "accent-yellow": "#fad23f",
          "off-white": "#FCFAED"
      },
      "borderRadius": {
          "DEFAULT": "0px",
          "lg": "0px",
          "xl": "0px",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Rajdhani"],
          "body": ["Plus Jakarta Sans"],
          "label": ["Rajdhani"]
      }
    },
  },
  plugins: [],
}
